apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/deployment.yaml
  - k8s/service.yaml

namespace: default

images:
  - name: gcr.io/PROJECT_ID/IMAGE:TAG
    newName: gcr.io/${PROJECT_ID}/${IMAGE}
    newTag: ${GITHUB_SHA}

commonLabels:
  app: cover-letter-generator
  environment: production

replicas:
  - name: cover-letter-generator
    count: 2